import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_excel('01.xlsx',header=None,skiprows=2, usecols='C:L', nrows=18)
# matrix = df.values
# print(matrix)

fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(14, 4))

x = ["96", "192", "288", "336", "528", "720"]
h1=df.iloc[0:6,0].tolist()
h2=df.iloc[0:6,2].tolist()
h3=df.iloc[0:6,4].tolist()
h4=df.iloc[0:6,6].tolist()
h5=df.iloc[0:6,8].tolist()
custom_ticks = [0.15, 0.20, 0.25, 0.30, 0.35]  # 自定义刻度值
ax1.set_yticks(custom_ticks)
ax1.set_ylim(0.14, 0.38)
ax1.axvline('96', color='0.7', linestyle='-', lw=1)
ax1.axvline('192', color='0.7', linestyle='-', lw=1)
ax1.axvline('288', color='0.7', linestyle='-', lw=1)
ax1.axvline('336', color='0.7', linestyle='-', lw=1)
ax1.axvline('528', color='0.7', linestyle='-', lw=1)
ax1.axvline('720', color='0.7', linestyle='-', lw=1)
ax1.plot(x, h1, label='iTransformer',color='red', linestyle='-', linewidth=1.2,marker='o',markersize=8,markerfacecolor='red', markeredgecolor='none')
ax1.plot(x, h2, label='Crossformer',color='orange', linestyle='-', linewidth=1.2,marker='s',markersize=8,markerfacecolor='orange', markeredgecolor='none')
ax1.plot(x, h3, label='FEDformer',color='green', linestyle='-', linewidth=1.2,marker='v',markersize=8,markerfacecolor='green', markeredgecolor='none')
ax1.plot(x, h4, label='Autoformer',color='purple', linestyle='-', linewidth=1.2,marker='p',markersize=8,markerfacecolor='none', markeredgecolor='purple')
ax1.plot(x, h5, label='Transformer',color='blue', linestyle='-', linewidth=1.2,marker='o',markersize=8,markerfacecolor='none', markeredgecolor='blue')
ax1.set_ylabel('MSE')
ax1.set_title('Weather')

h1=df.iloc[6:12,0].tolist()
h2=df.iloc[6:12,2].tolist()
h3=df.iloc[6:12,4].tolist()
h4=df.iloc[6:12,6].tolist()
h5=df.iloc[6:12,8].tolist()
custom_ticks = [0.1, 0.3, 0.5, 0.7, 0.9]  # 自定义刻度值
ax2.set_yticks(custom_ticks)
ax2.set_ylim(0.05, 0.97)
ax2.axvline('96', color='0.7', linestyle='-', lw=1)
ax2.axvline('192', color='0.7', linestyle='-', lw=1)
ax2.axvline('288', color='0.7', linestyle='-', lw=1)
ax2.axvline('336', color='0.7', linestyle='-', lw=1)
ax2.axvline('528', color='0.7', linestyle='-', lw=1)
ax2.axvline('720', color='0.7', linestyle='-', lw=1)
ax2.plot(x, h1,color='red', linestyle='-', linewidth=1.2,marker='o',markersize=8,markerfacecolor='red', markeredgecolor='none')
ax2.plot(x, h2,color='orange', linestyle='-', linewidth=1.2,marker='s',markersize=8,markerfacecolor='orange', markeredgecolor='none')
ax2.plot(x, h3,color='green', linestyle='-', linewidth=1.2,marker='v',markersize=8,markerfacecolor='green', markeredgecolor='none')
ax2.plot(x, h4,color='purple', linestyle='-', linewidth=1.2,marker='p',markersize=8,markerfacecolor='none', markeredgecolor='purple')
ax2.plot(x, h5,color='blue', linestyle='-', linewidth=1.2,marker='o',markersize=8,markerfacecolor='none', markeredgecolor='blue')
ax2.set_ylabel('MSE')
ax2.set_title('Exchange')

h1=df.iloc[12:18,0].tolist()
h2=df.iloc[12:18,2].tolist()
h3=df.iloc[12:18,4].tolist()
h4=df.iloc[12:18,6].tolist()
h5=df.iloc[12:18,8].tolist()
custom_ticks = [0.12, 0.16, 0.20,0.24,0.28]  # 自定义刻度值
ax3.set_yticks(custom_ticks)
ax3.set_ylim(0.116, 0.29)
ax3.axvline('96', color='0.7', linestyle='-', lw=1)
ax3.axvline('192', color='0.7', linestyle='-', lw=1)
ax3.axvline('288', color='0.7', linestyle='-', lw=1)
ax3.axvline('336', color='0.7', linestyle='-', lw=1)
ax3.axvline('528', color='0.7', linestyle='-', lw=1)
ax3.axvline('720', color='0.7', linestyle='-', lw=1)
ax3.plot(x, h1,color='red', linestyle='-', linewidth=1.2,marker='o',markersize=8,markerfacecolor='red', markeredgecolor='none')
ax3.plot(x, h2,color='orange', linestyle='-', linewidth=1.2,marker='s',markersize=8,markerfacecolor='orange', markeredgecolor='none')
ax3.plot(x, h3,color='green', linestyle='-', linewidth=1.2,marker='v',markersize=8,markerfacecolor='green', markeredgecolor='none')
ax3.plot(x, h4,color='purple', linestyle='-', linewidth=1.2,marker='p',markersize=8,markerfacecolor='none', markeredgecolor='purple')
ax3.plot(x, h5,color='blue', linestyle='-', linewidth=1.2,marker='o',markersize=8,markerfacecolor='none', markeredgecolor='blue')
ax3.set_ylabel('MSE')
ax3.set_title('Electricity')

fig.legend(loc='lower center',ncol=5, fontsize=8,mode='compact',labelspacing=1.0)
plt.subplots_adjust(bottom=0.13)
#plt.tight_layout()

plt.show()